# Pytest
[tool.pytest.ini_options]
pythonpath = ["btd6bot"]
addopts = [
    "--import-mode=importlib"
]

# Ruff
[tool.ruff]
exclude = [
    "docs",
    "btd6bot/plans",
    "btd6bot/_ocr_tests"
]

[tool.ruff.lint]
select = ["E4"]

[tool.ruff.lint.per-file-ignores]
"set_plan.py" = ["E402"]
"gui/main_window.py" = ["E402"]